import type { Listing } from "@/types/listing";

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Furnished Room Near PATH",
    city: "Jersey City",
    state: "NJ",
    address: "Downtown Jersey City",
    monthlyRent: 1650,
    roomType: "Private room",
    furnished: true,
    availableFrom: "June 1",
    availableUntil: "August 31",
    commute: "18 minutes to Midtown",
    ownerName: "Alex",
    description:
      "A bright, furnished private room in a clean shared apartment near the PATH station. The apartment is located in a quiet residential area with easy access to Manhattan, restaurants, grocery stores, and waterfront parks.",
    amenities: [
      "Wi-Fi",
      "In-unit laundry",
      "Air conditioning",
      "Desk and chair",
      "Full kitchen",
      "Near public transit",
    ],
  },
  {
    id: "2",
    title: "Summer Studio Near Midtown",
    city: "New York",
    state: "NY",
    address: "Murray Hill, Manhattan",
    monthlyRent: 2100,
    roomType: "Studio",
    furnished: true,
    availableFrom: "May 20",
    availableUntil: "August 20",
    commute: "8-minute walk to Midtown offices",
    ownerName: "Maya",
    description:
      "A compact furnished studio designed for a comfortable summer stay. The apartment includes a private kitchen and bathroom and is within walking distance of major Midtown offices.",
    amenities: [
      "Wi-Fi",
      "Private bathroom",
      "Kitchen",
      "Air conditioning",
      "Elevator",
      "Doorman",
    ],
  },
  {
    id: "3",
    title: "Private Room Near Columbia",
    city: "New York",
    state: "NY",
    address: "Morningside Heights, Manhattan",
    monthlyRent: 1450,
    roomType: "Private room",
    furnished: false,
    availableFrom: "June 10",
    availableUntil: "September 1",
    commute: "6-minute walk to the subway",
    ownerName: "Jordan",
    description:
      "A quiet private room in a shared apartment near Columbia University. It is a good option for students and interns looking for an affordable summer stay with convenient subway access.",
    amenities: [
      "Wi-Fi",
      "Shared kitchen",
      "Laundry in building",
      "Near subway",
      "Grocery stores nearby",
    ],
  },
];